version: '3'

services:
  opendevin-backend:
    image: localhost:5000/opendevin-runtime:latest                   
    command:
      - run backend --port 3000
    ports:
      - 3000:3000
    networks:
      - opendevin_net
    labels:
      - com.docker.stack.namespace=opendevin
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: opendevin_app
        target: /app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4.0'
          memory: 8G

  opendevin-frontend:
    image: localhost:5000/opendevin-runtime:latest
    command:
      - run frontend --port 3001
    ports:
      - 3001:3001
    networks:
      - opendevin_net
    labels:
      - com.docker.stack.namespace=opendevin
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: opendevin_app
        target: /app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  opendevin_app:
    driver: local
    driver_opts:
      type: none
      device: ../data/opendevin/app
      o: bind

networks:
  opendevin_net:
    driver: overlay
    external: true
    name: opendevin_net